import Container from "@mui/material/Container";
import type { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { Copyright } from "../components/Copyright";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import Hero from "../views/Hero";
import HowItWorks from "../views/HowItWorks";
import Values from "../views/Values";

const Home: NextPage = () => {
  const { data: session, status } = useSession();
  const loading = status === "loading";
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        {(loading && <>loading</>) || <>Welcome, {session?.user?.name}</>}
      </Container>
      <Copyright />
    </div>
  );
};

export default Home;
