import type { NextPage } from "next";
import Head from "next/head";
import { Copyright } from "../components/Copyright";
import Header from "../components/Header";
import LoginButton from "../components/LoginButton";
import styles from "../styles/Home.module.css";

const SignUp: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <LoginButton />

      <Copyright />
    </div>
  );
};

export default SignUp;
